name: StubbornWriter
favicon: null
layout_spectrum: 0.21618568431586027
typography_spectrum: 0.1377561572007835
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.0031905744690448046
  lightness: 0.3126007972750813
  saturation: 0.9863392908591777
  rhythmicContrast: 0.2609861702658236
purpose: []
